package datasources

import (
	"context"
	"fmt"
	"terraform-provider-sleep/internal/sleep"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ datasource.DataSource              = &sleeperDataSource{}
	_ datasource.DataSourceWithConfigure = &sleeperDataSource{}
)

func NewSleeper() datasource.DataSource {
	return &sleeperDataSource{}
}

type sleeperDataSource struct {
	sleeper sleep.Sleeper
}

type sleeperModel struct {
	Id        types.String `tfsdk:"id"`
	ReadSleep types.Number `tfsdk:"read_sleep"`
	StringIn  types.String `tfsdk:"string_in"`
	StringOut types.String `tfsdk:"string_out"`
}

func (d *sleeperDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sleeper"
}

func (d *sleeperDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:    true,
				Description: "The id of the datasource. This can be any random string value since this provider stores no information",
			},
			"read_sleep": schema.NumberAttribute{
				Optional:    true,
				Description: "The number of seconds the provider should sleep before returning from ReadData. If not provided, it will use a random value between [0,N] where N is the maximum number of seconds configured at the provider level.",
			},
			"string_in": schema.StringAttribute{
				Optional:    true,
				Description: "An optional field that will be used to be returned by the data source in the `string_out` attribute",
			},
			"string_out": schema.StringAttribute{
				Computed:    true,
				Description: "Value that will be generated by the data source. It uses the information passed into `string_in` or if that is missing, it will use the value of the `id` attribute",
			},
		},
	}
}

func (d *sleeperDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var cfg sleeperModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	cfg.StringOut = cfg.StringIn
	if cfg.StringOut.IsNull() {
		cfg.StringOut = cfg.Id
	}
	d.sleeper.Sleep(ctx, cfg.ReadSleep)
	resp.Diagnostics.Append(resp.State.Set(ctx, &cfg)...)
}

func (d *sleeperDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(sleep.Sleeper)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Sleeper type",
			fmt.Sprintf("Expected sleep.Sleeper, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.sleeper = c
}
