package ephemerals

import (
	"context"
	"fmt"
	"math/big"
	"strconv"
	"strings"
	"terraform-provider-sleep/internal/sleep"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ ephemeral.EphemeralResource              = &sleeperEphemeral{}
	_ ephemeral.EphemeralResourceWithRenew     = &sleeperEphemeral{}
	_ ephemeral.EphemeralResourceWithClose     = &sleeperEphemeral{}
	_ ephemeral.EphemeralResourceWithConfigure = &sleeperEphemeral{}
)

func NewSleeper() ephemeral.EphemeralResource {
	return &sleeperEphemeral{}
}

type sleeperEphemeral struct {
	sleeper sleep.Sleeper
}

type sleeperModel struct {
	Id         types.String `tfsdk:"id"`
	RenewDelay types.String `tfsdk:"renew_delay"`
	OpenSleep  types.Number `tfsdk:"open_sleep"`
	CloseSleep types.Number `tfsdk:"close_sleep"`
	RenewSleep types.Number `tfsdk:"renew_sleep"`
	StringIn   types.String `tfsdk:"string_in"`
	StringOut  types.String `tfsdk:"string_out"`
}

func (d *sleeperEphemeral) Metadata(_ context.Context, req ephemeral.MetadataRequest, resp *ephemeral.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sleeper"
}

func (d *sleeperEphemeral) Schema(_ context.Context, _ ephemeral.SchemaRequest, resp *ephemeral.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:    true,
				Description: "The id of the ephemeral resource. This can be any random string value since this provider stores no information",
			},
			"open_sleep": schema.NumberAttribute{
				Optional:    true,
				Description: "The number of seconds the provider should sleep before returning from the Open call. If not provided, it will use a random value between [0,N] where N is the maximum number of seconds configured at the provider level.",
			},
			"renew_delay": schema.StringAttribute{
				Optional:    true,
				Description: "The number of seconds that the Open call will return. This is used by the caller system to know at which interval should call Renew",
			},
			"renew_sleep": schema.NumberAttribute{
				Optional:    true,
				Description: "The number of seconds the provider should sleep before returning from the Renew call. If not provided, it will use a random value between [0,N] where N is the maximum number of seconds configured at the provider level.",
			},
			"close_sleep": schema.NumberAttribute{
				Optional:    true,
				Description: "The number of seconds the provider should sleep before returning from the Close call. If not provided, it will use a random value between [0,N] where N is the maximum number of seconds configured at the provider level.",
			},
			"string_in": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "An optional field that will be used to be returned by the ephemeral resource in the `string_out` attribute",
			},
			"string_out": schema.StringAttribute{
				Computed:    true,
				Sensitive:   true,
				Description: "Value that will be generated by the ephemeral resource. It uses the information passed into `string_in` or if that is missing, it will use the value of the `id` attribute",
			},
		},
	}
}

func (d *sleeperEphemeral) Open(ctx context.Context, req ephemeral.OpenRequest, resp *ephemeral.OpenResponse) {
	var cfg sleeperModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}

	d.sleeper.Sleep(ctx, cfg.OpenSleep)

	var (
		renewAfter time.Duration

		renewSleep int
		closeSleep int
	)
	if !cfg.RenewDelay.IsNull() && !cfg.RenewDelay.IsUnknown() {
		rawRenewAfter, err := time.ParseDuration(cfg.RenewDelay.ValueString())
		if err != nil {
			resp.Diagnostics.Append(diag.NewErrorDiagnostic("Invalid renew_delay format", fmt.Sprintf("The value needs to be in duration format: 2s, 3m, etc. Error: %s", err)))
			return
		}
		renewAfter = rawRenewAfter
	}
	if !cfg.RenewSleep.IsNull() && !cfg.RenewSleep.IsUnknown() {
		renewSleep64, _ := cfg.RenewSleep.ValueBigFloat().Int64()
		renewSleep = int(renewSleep64)
	}
	if !cfg.CloseSleep.IsNull() && !cfg.CloseSleep.IsUnknown() {
		closeSleep64, _ := cfg.CloseSleep.ValueBigFloat().Int64()
		closeSleep = int(closeSleep64)
	}
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, "close_sleep", []byte(strconv.Itoa(closeSleep)))...)
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, "renew_sleep", []byte(strconv.Itoa(renewSleep)))...)
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, "renew_delay", []byte(fmt.Sprintf(`"%s"`, renewAfter.String())))...)
	if renewAfter > 0 {
		resp.RenewAt = time.Now().Add(renewAfter)
	}
	cfg.StringOut = cfg.StringIn
	if cfg.StringOut.IsNull() {
		cfg.StringOut = cfg.Id
	}
	resp.Diagnostics.Append(resp.Result.Set(ctx, &cfg)...)
}

func (d *sleeperEphemeral) Renew(ctx context.Context, req ephemeral.RenewRequest, resp *ephemeral.RenewResponse) {
	// process the `renew_sleep` and wait for the configured duration
	dat, diags := req.Private.GetKey(ctx, "renew_sleep")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	m, err := byteSliceToNumber(dat)
	if err != nil {
		resp.Diagnostics.Append(diag.NewErrorDiagnostic("Invalid configured renew_sleep", err.Error()))
		return
	}

	d.sleeper.Sleep(ctx, m)

	// process `renew_delay` to add that to the renew response.
	// This ensures that the caller will invoke Renew again in the initially configured `renew_delay`.
	rawRenewDelay, diags := req.Private.GetKey(ctx, "renew_delay")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	dur, err := time.ParseDuration(strings.ReplaceAll(string(rawRenewDelay), "\"", ""))
	if err != nil {
		resp.Diagnostics.Append(diag.NewErrorDiagnostic("Invalid format for renew_delay", err.Error()))
		return
	}
	// forward the private information since that contains information that is populated by Open and Renew/Close needs it.
	resp.Private = req.Private
	if dur > 0 {
		resp.RenewAt = time.Now().Add(dur)
	}
}

func (d *sleeperEphemeral) Close(ctx context.Context, req ephemeral.CloseRequest, resp *ephemeral.CloseResponse) {
	dat, diags := req.Private.GetKey(ctx, "close_sleep")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	m, err := byteSliceToNumber(dat)
	if err != nil {
		resp.Diagnostics.Append(diag.NewErrorDiagnostic("Invalid configured close_sleep", err.Error()))
		return
	}

	d.sleeper.Sleep(ctx, m)
}

func (d *sleeperEphemeral) Configure(ctx context.Context, req ephemeral.ConfigureRequest, resp *ephemeral.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(sleep.Sleeper)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Sleeper type",
			fmt.Sprintf("Expected sleep.Sleeper, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.sleeper = c
}

func byteSliceToNumber(in []byte) (types.Number, error) {
	m, err := strconv.ParseInt(string(in), 10, 64)
	if err != nil {
		return types.NumberNull(), err
	}
	return types.NumberValue(big.NewFloat(float64(m))), nil
}
